services:
  go-pot-node-1:
    container_name: go-pot-node-1
    build:
      context: ./../../
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./../../:/app:ro
    ports:
      - "8080:80"
    command: "go-pot"
    environment:
      - GOPOT__CLUSTER__ENABLED=true
      - GOPOT__CLUSTER__ADVERTISE_IP=10.5.0.4
      - GOPOT__CLUSTER__KNOWN_PEER_IPS=10.5.0.5
      - GOPOT__CLUSTER__LOGGING_ENABLED=true
    networks:
      go-pot-network:
        ipv4_address: 10.5.0.4

  go-pot-node-2:
    container_name: go-pot-node-2
    build:
      context: ./../../
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./../../:/app:ro
    ports:
      - "8081:80"
    environment:
      - GOPOT__CLUSTER__ENABLED=true
      - GOPOT__CLUSTER__ADVERTISE_IP=10.5.0.5
      - GOPOT__CLUSTER__KNOWN_PEER_IPS=10.5.0.6
      - GOPOT__CLUSTER__LOGGING_ENABLED=true
    networks:
      go-pot-network:
        ipv4_address: 10.5.0.5

  go-pot-node-3:
    container_name: go-pot-node-3
    build:
      context: ./../../
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./../../:/app:ro
    ports:
      - "8082:80"
    environment:
      - GOPOT__CLUSTER__ENABLED=true
      - GOPOT__CLUSTER__ADVERTISE_IP=10.5.0.6
      - GOPOT__CLUSTER__KNOWN_PEER_IPS=10.5.0.4
      - GOPOT__CLUSTER__LOGGING_ENABLED=true
    networks:
      go-pot-network:
        ipv4_address: 10.5.0.6

networks:
  go-pot-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1



    