global:
  scrape_interval: 15s
  scrape_timeout: 2s
  evaluation_interval: 15s
scrape_configs:
- job_name: push_gateway
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['10.5.0.9:9091']
    labels:
      service: 'prom-pushgateway'
