services:
  go_pot_behind_reverse_proxy:
    container_name: go_pot_behind_reverse_proxy
    build:
      context: ./../../
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./../../:/app:ro
    ports:
      - "8081:8080"
    command: "go-pot"
    environment:
      - GOPOT__SERVER__HOST=0.0.0.0
      - GOPOT__SERVER__PORT=8080
      - GOPOT__SERVER__TRUSTED_PROXIES=172.16.0.0/12
      - GOPOT__SERVER__PROXY_HEADER=X-Forwarded-For
  
  go_pot_nginx:
    image: nginx
    container_name: go_pot_nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - go_pot_behind_reverse_proxy

